package: bcbio-nextgen-vm
user: bcbio

platform:
  - linux-64
#  - osx-64
#  - win-64
engine:
 - python=2.7

install:
  - conda config --add channels https://conda.binstar.org/bcbio

script:
  - conda build .
  
build_targets:
 files: conda
 channels: main