package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 63

source:
  fn: bcbio-nextgen-vm-3c7027d1b0.tar.gz
  url: https://github.com/chapmanb/bcbio-nextgen-vm/archive/3c7027d1b0.tar.gz
  #git_url: https://github.com/chapmanb/bcbio-nextgen-vm.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - bcbio-nextgen
    - elasticluster
    - nose
    - six

test:
  imports:
    - bcbiovm.version

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT
  summary: Run bcbio-nextgen genomic sequencing analyses using isolated containers and virtual machines
