package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 15

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen-vm.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - bcbio-nextgen
    - nose
    - six
    - boto

test:
  imports:
    - bcbiovm.version

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT
  summary: Run bcbio-nextgen genomic sequencing analyses using isolated containers and virtual machines