package:
  name: cyvcf2
  version: '0.1.8'

source:
  fn: cyvcf2-0.1.8.tar.gz
  url: https://pypi.python.org/packages/source/c/cyvcf2/cyvcf2-0.1.8.tar.gz
  md5: cfe2e55343138663f546e3d7fa201298

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - seaborn
    - pandas

test:
  imports:
    - cyvcf2

about:
  home: https://github.com/brentp/cyvcf2
  summary: A cython wrapper around htslib built for fast parsing of Variant Call Format (VCF) files
  license: MIT
