package:
  name: pytabix
  version: 0.0.2

source:
  fn: pytabix-0.0.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pytabix/pytabix-0.0.2.tar.gz
  md5: c558be1d55a8b72c92668837305054e2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - tabix

about:
  home: https://github.com/slowkow/pytabix
  license: MIT
  summary: fast random access to sorted files compressed with bgzip and indexed by tabix