package:
  name: hmmlearn
  version: 20150818

source:
  fn: hmmlearn-66dcb9d.tar.gz
  url: https://github.com/hmmlearn/hmmlearn/archive/66dcb9d.tar.gz

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - scikit-learn

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - hmmlearn.hmm

about:
  home: https://github.com/hmmlearn/hmmlearn
  license: BSD
  summary: Hidden Markov Models in Python, with scikit-learn like API

