# Build conda packages and upload to binstar
---
- hosts: localhost
  connection: local
  vars:
    binstar_user: bcbio
    binstar_repo: https://conda.binstar.org/bcbio
  tasks:
    - name: Add binstar repo to conda configuration
      command: 'conda config --add channels {{binstar_repo}}'
    - name: Build conda packages and upload to binstar
      ignore_errors: true
      shell: >
       conda build --no-binstar-upload {{item}} &&
       binstar upload -u {{binstar_user}} `conda build --output {{item}}`
      with_items:
        - bx-python
        - netifaces
        - ipython-cluster-helper
        - gffutils
        - pyvcf
        - pysam
        - bcbio-nextgen
        - bcbio-nextgen-vm
        - cpat
        - cnvkit
