package:
  name: cpat
  version: 1.2.1

build:
  number: 2

source:
  fn: CPAT-1.2.1.tar.gz
  url: http://sourceforge.net/projects/rna-cpat/files/CPAT-1.2.1.tar.gz
  md5: e18ca349882502ffd684af7bcb426fc6
  patches:
    - setup.py.patch

requirements:
  build:
    - nose
    - numpy
    - cython
    - python
    - setuptools
    - bx-python
    - pysam

  run:
    - python
    - setuptools
    - bx-python
    - pysam

test:
  commands:
    - cpat.py -h
    - make_hexamer_tab.py -h
    - make_logitModel.py -h

about:
  home: http://dldcc-web.brc.bcm.edu/lilab/liguow/CGI/cpat/_build/html/index.html
  license: GNU
  summary: Coding Potential Assessment Tool
