package:
  name: bcbio-nextgen
  version: '0.8.9'

build:
  number: 0

source:
  fn: bcbio-nextgen-0.8.9.tar.gz
  url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.8.9.tar.gz
  url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.8.9.tar.gz
  md5: 44fd93a457d682eabfece15da5176423
  #fn: bcbio-nextgen-37c5b6e.tar.gz
  #url: https://github.com/chapmanb/bcbio-nextgen/archive/37c5b6e.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - argparse [py26]
    - biopython
    - boto
    - bx-python
    - cpat
    - cython
    - gffutils
    - ipython
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - numpy
    - pandas
    - progressbar
    - pybedtools
    - pysam
    - pyvcf
    - pyyaml
    - pyzmq
    - requests
    - seaborn
    - scipy
    - toolz
    - tornado

test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis
