package:
  name: bcbio-nextgen
  version: '0.8.4a'

build:
  number: 0

source:
  #fn: bcbio-nextgen-0.8.0.tar.gz
  #url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.8.0.tar.gz
  #md5: 5d9ec2eed5915cc4fd9788923040dda6
  git_url: https://github.com/chapmanb/bcbio-nextgen.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - argparse [py26]
    - biopython
    - boto
    - bx-python
    - cpat
    - gffutils
    - ipython
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - msgpack-python
    - pandas
    - pysam
    - pyvcf
    - pyyaml
    - pyzmq
    - requests
    - toolz
    - tornado

test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis
