package:
  name: bcbio-nextgen
  version: '0.9.4a0'

build:
  number: 2

source:
  #fn: bcbio-nextgen-0.9.3.tar.gz
  #url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.9.3.tar.gz
  fn: bcbio-nextgen-6fae1db.tar.gz
  url: https://github.com/chapmanb/bcbio-nextgen/archive/6fae1db.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - argparse [py26]
    - azure
    - biopython
    - boto
    - bx-python
    - cpat
    - cython
    - gffutils
    - ipyparallel
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - numpy
    - pandas
    - progressbar
    - psutil
    - pybedtools
    - pysam
    - pythonpy
    - pyvcf
    - pyyaml
    - pyzmq
    - requests
    - seaborn
    - scipy
    - toolz
    - tornado

test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis