package:
  name: bcbio-nextgen
  version: '0.9.1a'

build:
  number: 1

source:
  #fn: bcbio-nextgen-0.9.0.tar.gz
  #url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.9.0.tar.gz
  #md5: d913ecd9acc270319199a6f28e2c1af8
  fn: bcbio-nextgen-63a013c.tar.gz
  url: https://github.com/chapmanb/bcbio-nextgen/archive/63a013c.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - argparse [py26]
    - azure
    - biopython
    - boto
    - bx-python
    - cpat
    - cython
    - gffutils
    - ipython
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - numpy
    - pandas
    - progressbar
    - pybedtools
    - pysam
    - pyvcf
    - pyyaml
    - pyzmq
    - requests
    - seaborn
    - scipy
    - toolz
    - tornado

test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling and RNA-seq analysis
