package:
  name: htseq
  version: '0.6.1'

source:
  fn: HTSeq-0.6.1.tar.gz
  url: https://pypi.python.org/packages/source/H/HTSeq/HTSeq-0.6.1.tar.gz
  md5: b7f4f38a9f4278b9b7f948d1efbc1f05

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - setuptools
    - numpy

test:
  commands:
    - htseq-count -h

about:
  home: http://www-huber.embl.de/users/anders/HTSeq/doc/index.html
  license: GPLv3
  summary: A framework to process and analyze data from high-throughput sequencing (HTS) assays
