package:
  name: ipython-cluster-helper
  version: 0.4.8

source:
  fn: ipython-cluster-helper-0.4.8.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython-cluster-helper/ipython-cluster-helper-0.4.8.tar.gz

requirements:
  build:
    - python
    - setuptools
    - netifaces

  run:
    - python
    - setuptools
    - ipyparallel
    - pyzmq
    - netifaces

test:
  imports:
    - cluster_helper.cluster

about:
  home: https://github.com/roryk/ipython-cluster-helper
  license: MIT
  summary: Tool to easily start up an IPython cluster on different schedulers