package:
  name: ipython-cluster-helper
  version: 0.2.24

source:
  fn: ipython-cluster-helper-0.2.24.tar.gz
  url: https://pypi.python.org/packages/source/i/ipython-cluster-helper/ipython-cluster-helper-0.2.24.tar.gz
  md5: be89cfd0413b5d755c2751f0a9e12e23

requirements:
  build:
    - python
    - setuptools
    - netifaces

  run:
    - python
    - setuptools
    - ipython
    - pyzmq
    - netifaces

test:
  imports:
    - cluster_helper.cluster

about:
  home: https://github.com/roryk/ipython-cluster-helper
  license: MIT
  summary: Tool to easily start up an IPython cluster on different schedulers