package:
  name: hap.py
  version: '0.2.0'

source:
  fn: hap.py-0.2.0.tar.gz
  url: https://github.com/sequencing/hap.py/archive/v0.2.0-public.tar.gz
  md5: 57ba6d46e9d96eeaa142ab36eb45fff1

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - pandas
    - pybedtools
    - pysam
    - nose
    - bx-python

  run:
    - python
    - cython
    - numpy
    - pandas
    - pybedtools
    - pysam
    - nose
    - bx-python

#test:
#  commands:
#    - hap.py -h
#    - som.py -h

about:
  home: https://github.com/sequencing/hap.py
  license: BSD
