package:
  name: bcdoc
  version: '0.13.0'

source:
  fn: bcdoc-0.13.0.tar.gz
  url: https://pypi.python.org/packages/source/b/bcdoc/bcdoc-0.13.0.tar.gz
  md5: 819882458be7b642e00ddc9846073d89

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six
    - docutils

  run:
    - python
    - setuptools
    - six
    - docutils

test:
  imports:
    - bcdoc

about:
  home: https://github.com/boto/bcdoc
  license: Apache License 2.0
