package:
  name: botocore
  version: '0.95.0'

source:
  fn: botocore-0.95.0.tar.gz
  url: https://pypi.python.org/packages/source/b/botocore/botocore-0.95.0.tar.gz
  md5: 55de179effcbb7083887ee951fba6321

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - jmespath
    - python-dateutil

  run:
    - python
    - setuptools
    - jmespath
    - python-dateutil

test:
  imports:
    - botocore

about:
  home: https://github.com/boto/botocore
  license: Apache License 2.0
