package:
  name: metasv
  version: '0.3.2a'

source:
  fn: metasv-8e77859.tar.gz
  url: https://github.com/chapmanb/metasv/archive/8e77859.tar.gz

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - cython
    - pybedtools
    - pyvcf
    - pysam

  run:
    - python
    - pybedtools
    - pyvcf
    - pysam

test:
  commands:
    - run_metasv.py -h

about:
  home: https://github.com/bioinform/metasv
  summary: An accurate and integrative structural-variant caller for next generation sequencing
  license: MIT
