package:
  name: metasv
  version: '0.4.0'

source:
  #fn: metasv-0.3.2a0.tar.gz
  #url: https://github.com/bioinform/metasv/archive/0.3.2a0.tar.gz

  fn: metasv-d55bf34.tar.gz
  url: https://github.com/bioinform/metasv/archive/d55bf34.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - pybedtools
    - pyvcf
    - pysam

  run:
    - python
    - pybedtools
    - pyvcf
    - pysam

test:
  commands:
    - run_metasv.py -h

about:
  home: https://github.com/bioinform/metasv
  summary: An accurate and integrative structural-variant caller for next generation sequencing
  license: MIT
