package:
  name: svtyper
  version: 0.0.2

source:
  fn: svtyper-0.0.2.tar.gz
  url: https://github.com/hall-lab/svtyper/archive/v0.0.2.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pysam

  run:
    - python
    - setuptools
    - pysam

test:
  commands:
    - svtyper -h

about:
  home: https://github.com/hall-lab/svtyper
  license: MIT
  summary: Bayesian genotyper for structural variants

