package:
  name: bx-python
  version: '0.7.2'

source:
  #hg_url: https://bitbucket.org/james_taylor/bx-python
  fn: bx-python-0.7.2.tar.gz
  url: https://pypi.python.org/packages/source/b/bx-python/bx-python-0.7.2.tar.gz
  md5: 113d0c755b3c7cb38bf95d069105b299
  patches:
    - setup.patch

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - nose
    - numpy

  run:
    - python
    - setuptools
    - numpy

test:
  imports:
    - bx.align.sitemask
    - bx.tabular
    - bx.intervals
    - bx.align
    - bx.bbi
    - bx.cookbook
    - bx.arrays
    - bx.motif.io
    - bx.seq
    - bx.intervals.operations
    - bx.pwm
    - bx.misc
    - bx.motif
    - bx.phylo
    - bx.motif.logo
    - bx_extras
    - bx.align.tools
    - bx
    - bx.intseq

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://bitbucket.org/james_taylor/bx-python/wiki/Home
  license: MIT
  summary: Toolkit to enable rapid implementation of genome scale analyses.
