package:
  name: cnvkit
  version: '0.3.5'

source:
  #fn: CNVkit-0.3.5.tar.gz
  #url: https://pypi.python.org/packages/source/C/CNVkit/CNVkit-0.3.5.tar.gz
  #md5: c95ddad501dd76161af64e19b1261f15
  git_url: https://github.com/etal/cnvkit.git

build:
  number: 4

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - numpy
    - scipy
    - matplotlib
    - biopython
    - reportlab
    - pysam
    - pyvcf

test:
  # Python imports
  imports:
    - cnvlib

about:
  home: https://github.com/etal/cnvkit
  license: MIT
  summary: Copy number variant detection from targeted DNA sequencing
