package:
  name: cnvkit
  version: '0.5.0'

source:
  fn: CNVkit-0.5.0.tar.gz
  url: https://pypi.python.org/packages/source/C/CNVkit/CNVkit-0.5.0.tar.gz
  md5: 90e8bb79c93e5194f43d16f26d0398eb
  #git_url: https://github.com/chapmanb/cnvkit.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - numpy
    - scipy
    - matplotlib
    - biopython
    - reportlab
    - pysam
    - pyvcf

test:
  # Python imports
  imports:
    - cnvlib

about:
  home: https://github.com/etal/cnvkit
  license: MIT
  summary: Copy number variant detection from targeted DNA sequencing
