package:
  name: cnvkit
  version: '0.4.1'

source:
  #fn: CNVkit-0.4.1.tar.gz
  #url: https://pypi.python.org/packages/source/C/CNVkit/CNVkit-0.4.1.tar.gz
  #md5: 4c4241966a27a28cdf1c3bfd6eeca47b
  git_url: https://github.com/chapmanb/cnvkit.git

build:
  number: 4

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - numpy
    - scipy
    - matplotlib
    - biopython
    - reportlab
    - pysam
    - pyvcf

test:
  # Python imports
  imports:
    - cnvlib

about:
  home: https://github.com/etal/cnvkit
  license: MIT
  summary: Copy number variant detection from targeted DNA sequencing
