package:
  name: cnvkit
  version: '0.6.2a'

source:
  fn: CNVkit-7bcf86e.tar.gz
  url: https://github.com/etal/cnvkit/archive/7bcf86e.tar.gz
  #fn: CNVkit-0.6.1.tar.gz
  #url: https://pypi.python.org/packages/source/C/CNVkit/CNVkit-0.6.1.tar.gz

build:
  number: 2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - numpy
    - scipy
    - pandas
    - matplotlib
    - biopython
    - reportlab
    - pysam
    - pyvcf

test:
  # Python imports
  imports:
    - cnvlib

about:
  home: https://github.com/etal/cnvkit
  license: MIT
  summary: Copy number variant detection from targeted DNA sequencing
