package:
  name: gffutils
  version: 0.8.3

source:
  fn: gffutils-0.8.3.tar.gz
  url: https://pypi.python.org/packages/source/g/gffutils/gffutils-0.8.3.tar.gz
  md5: bed16cfed2137d8e467eb71495813fbf

requirements:
  build:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

  run:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

test:
  imports:
    - gffutils

about:
  home: https://github.com/daler/gffutils
  license: MIT
  summary: GFF and GTF file manipulation and interconversion