package:
  name: gffutils
  version: 0.8.3.1

source:
  fn: gffutils-0.8.3.1.tar.gz
  url: https://pypi.python.org/packages/source/g/gffutils/gffutils-0.8.3.1.tar.gz
  md5: 69b0a47ad1acbd809c68d930044a11ae

requirements:
  build:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

  run:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

test:
  imports:
    - gffutils

about:
  home: https://github.com/daler/gffutils
  license: MIT
  summary: GFF and GTF file manipulation and interconversion
