package:
  name: gffutils
  version: 0.8.4rc1

source:
  fn: gffutils-0.8.4rc1.tar.gz
  url: https://pypi.python.org/packages/source/g/gffutils/gffutils-0.8.4rc1.tar.gz
  md5: 9d46b3dfac35ad812df2448f20c5e8cc

requirements:
  build:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

  run:
    - python
    - setuptools
    - simplejson
    - six
    - pyfaidx
    - biopython

test:
  imports:
    - gffutils

about:
  home: https://github.com/daler/gffutils
  license: MIT
  summary: GFF and GTF file manipulation and interconversion
