package:
  name: phylowgs
  version: '20150701'

source:
  fn: phylowgs-2d555c9.tar.gz
  url: https://github.com/chapmanb/phylowgs/archive/2d555c9.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - ete2
    - gsl

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - ete2
    - gsl

#test:
#  commands:
#    - evolve.py -h

about:
  home: https://github.com/morrislab/phylowgs
  license: GPLv3
  summary:  Application for inferring subclonal composition and evolution from whole-genome sequencing data
