package:
  name: pyloh
  version: '1.4.0'

source:
  fn: pyloh-1.4.0.tar.gz
  url: https://github.com/uci-cbcl/PyLOH/archive/1.4.0.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pysam

test:
  imports:
    - pyloh

about:
  home: https://github.com/uci-cbcl/PyLOH
  license: GPL
  summary: Deconvolving tumor purity and ploidy by integrating copy number alterations and loss of heterozygosity
