package:
  name: oauth2client
  version: '1.4.6'

source:
  fn: oauth2client-1.4.6.tar.gz
  url: https://pypi.python.org/packages/source/o/oauth2client/oauth2client-1.4.6.tar.gz
  md5: bce90994cc917de8b1042465561ce3c6

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - httplib2
    - pyasn1
    - pyasn1-modules
    - rsa
    - six

test:
  imports:
    - oauth2client
    - oauth2client.client

about:
  home: https://github.com/google/oauth2client/
  license: Apache 2.0
