package:
  name: ansible
  version: 1.9.3

# Updated version of ansible package from Barnaby Gray:
# https://github.com/barnybug/conda-recipes/tree/master/ansible

source:
  fn: ansible-1.9.3.tar.gz
  url: https://pypi.python.org/packages/source/a/ansible/ansible-1.9.3.tar.gz
  md5: 55be10fca4e9e0172a15e88874028eff

requirements:
  build:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - pycrypto
    - six

  run:
    - python
    - setuptools
    - paramiko
    - jinja2
    - pyyaml
    - httplib2
    - pycrypto
    - six

test:
  imports:
    - ansible
    - ansible.constants
    - ansible.errors
    - ansible.playbook
    - ansible.utils
  commands:
    - ansible -h

about:
  home: http://www.ansible.com/
  license: GPLv3
  summary: Radically simple IT automation
