package:
  name: pysam
  version: '0.8.2.1'

source:
  fn: pysam-0.8.2.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.8.2.1.tar.gz
  md5: daf63c1665fa601fc942f050f334a627

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  imports:
    - pysam
    - pysam.include

about:
  home: http://code.google.com/p/pysam/
  license: MIT
