package:
  name: pysam
  version: '0.8.1'

source:
  fn: pysam-0.8.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.8.1.tar.gz
  md5: 9b2c7b4c1ea63841815725557da188fb

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  imports:
    - pysam
    - pysam.include

about:
  home: http://code.google.com/p/pysam/
  license: MIT
