package:
  name: pysam
  version: '0.8.3'

source:
  #fn: pysam-0.8.3.tar.gz
  #url: https://pypi.python.org/packages/source/p/pysam/pysam-0.8.3.tar.gz
  fn: pysam-e582665.tar.gz
  url: https://github.com/pysam-developers/pysam/archive/e582665.tar.gz
  md5: 2622ae8087ce1a72eeb6028e3a2d6a26

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  imports:
    - pysam
    - pysam.include

about:
  home: http://code.google.com/p/pysam/
  license: MIT
