package:
  name: pysam
  version: '0.7.7'

source:
  fn: pysam-0.7.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.7.7.tar.gz
  md5: eaf9f37cbccc5e2708754d045909c1a0

build:
  number: 2

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  # Python imports
  imports:
    - pysam
    - pysam.include
    - pysam.include.samtools
    - pysam.include.tabix
    - pysam.include.samtools.bcftools

about:
  home: http://code.google.com/p/pysam/
  license: MIT
