package:
  name: pysam
  version: '0.8.3'

source:
  fn: pysam-0.8.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.8.3.tar.gz
  md5: b1ae2a8ec3c6d20be30b2bc1aa995bbf

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  imports:
    - pysam
    - pysam.include

about:
  home: http://code.google.com/p/pysam/
  license: MIT
