package:
  name: pysam
  version: '0.8.0'

source:
  fn: pysam-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.8.0.tar.gz
  md5: 7c5ddff512b86ac358810317340be077

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython

  run:
    - python

test:
  # Python imports
  imports:
    - pysam
    - pysam.include
    - pysam.include.htslib
    - pysam.include.samtools
    - pysam.include.samtools.bcftools

about:
  home: http://code.google.com/p/pysam/
  license: MIT
