package:
  name: pyfaidx
  version: 0.4.1.1

source:
  fn: pyfaidx-0.4.1.1.tar.gz
  url: https://github.com/mdshw5/pyfaidx/archive/v0.4.1.1.tar.gz

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - setuptools
    - six

test:
  imports:
    - pyfaidx

about:
  home: https://github.com/mdshw5/pyfaidx
  license: MIT
  summary: efficient pythonic random access to fasta subsequences